Ohtu-org/Serverless-data-parser-tool-for-project-proposals

front/package-lock.json
front/package.json
front/public/index.html
front/src/components/Messages.js
front/src/components/Words.js
front/src/services/messages.js

User can discern different sections of the user interface

---

.github/workflows/main.yml
.gitignore
front/.eslintignore
front/.eslintrc.js
front/.gitignore
front/package-lock.json
front/package.json
front/src/App.js
front/src/components/DemoHome.js
front/src/components/Messages.js
front/src/components/Words.js
front/src/index.js
front/src/reducers/dataReducer.js
front/src/services/messages.js
front/src/store.js
package-lock.json

Added eslint to frontend, fixed errors and added front lint to Worklfow.

Lint to frontend

---

backend/.gitignore
backend/app.js
backend/utils/filterSlackResponse.js
backend/utils/importHistory.js

Backend calls another API which gets replies to threads from a single channel from the test workspace.

Message parsing including threads

---

backend/utils/filterSlackResponse.js
backend/utils/importHistory.js
front/src/components/Words.js

Instead of a list of words backend creates list of objects that hold the word, number of occurances and message ids it was mentioned.
Modified front component Words to change.

User can tag important words

---

backend/.eslintrc.js
backend/app.js
backend/tests/unit/parseSlackTimestamp.test.js
backend/utils/filterSlackResponse.js
backend/utils/importHistory.js
backend/utils/parseSlackTimestamp.js
backend/utils/slackChannels.js
backend/utils/slackUsers.js
front/src/components/Words.js

Right now only parameter working is channel, but should merge to avoid merge conflicts building up.   
Also new feature: backend serves lists of channels and users to use in frontend for parameter choices.

User should be able to define parameters

---

front/src/components/Messages.js

First draft of frontend showing all messages even from threads.

Frontend shows all messages if message is a thread

---

backend/tests/unit/filterOutOldMessages.test.js

Tests for new timefilter

---

front/package-lock.json
front/src/components/UserForm.js
front/src/reducers/channelReducer.js

Made front userForm use channels from backend and changed UserForm to use only MUI.

Userform uses excisting channels and changed button design

---

front/src/components/UserForm.js
front/src/components/Words.js

Got away with console errors, by adding default value to channel select and changing typography to grid in Words.

Paramters to choose

---

backend/app.js
backend/utils/filterSlackResponse.js
backend/utils/importHistory.js

Backend refactoring

---

front/src/App.js
front/src/components/AssignedWords.js
front/src/components/Word.js
front/src/pages/HomePage.js
front/src/reducers/assignReducer.js
front/src/reducers/categoriesReducer.js
front/src/store.js

Assign relevant data to fields

---

README.md

Link to product backlog added to readme

---

backend/tests/unit/assignCategoryToWord.test.js
backend/tests/unit/getWordsFromMessages.test.js
backend/utils/assignCategoryToWord.js

Category finds words that are or include numbers.

Words with numbers are assigned category: 'Number'

---

backend/application/filterSlackResponse.js
backend/tests/unit/getWordsFromMessages.test.js
backend/tests/unit/testMessages.js
backend/utils/languageConstants.js
backend/utils/utilityConstants.js

First version of filter removes few hundred filler words.

Filter filler words

---

backend/app.js
backend/controllers/slackController.js
backend/services/slackService.js

Slash command /parse [channel][hours] works in the test parsing workspace. Next steps possibly refactoring, fix to work with 3 parameters ( channel, user, hours), communicating with frontend (possibly using react router would be handy) and of course tests.

Slash command

---

backend/application/filterSlackResponse.js
backend/tests/unit/assignCategoryToWord.test.js
backend/utils/assignCategoryToWord.js

Not the prettiest way to do it, but it works. ParsedWords checks once if a word has a category, if a category is found, no special characters are removed. Later the category is checked again an added to word.

Fixed date parsing and Number category error

---

backend/app.js
backend/application/filterSlackResponse.js
backend/application/processSlackMessages.js
backend/controllers/slackController.js
backend/services/slackService.js
backend/utils/parseParameters.js

Slash command works now with 3 parameters. It is assumed that the user gives nicely all the 3 parameters in form: /parse channel user hours. Implementing command with 1 or 2 parameters should be discussed at some point. Command returns an url which shows the wanted data.

Slash command works with 3 parameters

---

README.md
backend/app.js
backend/utils/parseParameters.js

Accepts any amount of parameters <= 3 and in any order.

Slashcommandtest

---

backend/app.js
front/src/components/SendToHubspot.js
front/src/reducers/assignReducer.js
front/src/reducers/sendReducer.js
front/src/services/sendJSON.js
front/src/store.js

Click on button parses JSON and sends to endpoint at backend.

Create JSON and send to backend

---

backend/app.js
backend/controllers/hubspotController.js
backend/package-lock.json
backend/package.json
backend/services/hubspotClient.js
backend/services/hubspotService.js
front/src/reducers/sendReducer.js

First version for testing and front developement.
Creates new deal with name from customer field and amount from price. Custom properties are not implemented yet. Conversion from obj.Price (String in ui) to number is dodgy. Should conv happen in ui so user can see the number.?

Send data to hubspot

---

cypress/integration/data_parser_spec.js
front/src/components/Messages.js
front/src/components/SendToHubspot.js
front/src/components/Word.js
front/src/components/Words.js
front/src/reducers/sendReducer.js
front/src/tests/sendReducer.test.js

Hopefully the elint-fixes are actually working this time around.

Cypress tests in the green and new front tests and better SendToHubSpot-front-solution

---

backend/app.js
backend/controllers/slackController.js
backend/tests/unit/slackController.test.js

Separated slackResponse to own function to be able to test it. Added a few tests for slack response.

Tests for slackbot response

---

backend/controllers/slackController.js

More verbose response message

---

.github/workflows/main.yml
.gitignore
README.md
backend/application/filterSlackResponse.js
backend/application/processMessageShortcut.js

Testing if codecov coverage works in CI job and also documented some code.

Testing if Codecov coverage works, merging this myself

---

backend/app.js
backend/controllers/slackController.js
front/src/App.js
front/src/components/DrawerParameters.js
front/src/components/ParametersForm.js
front/src/reducers/parameterReducer.js

Reverts Ohtu-org/Serverless-data-parser-tool-for-project-proposals#103
Reverting because is missing a file which causes build errors and cypress tests to explode.

Revert "Get's parameters from backend and adds to frontend left side field"

---

backend/app.js
backend/controllers/slackController.js
front/src/App.js
front/src/components/DrawerParameters.js
front/src/components/ParametersForm.js
front/src/reducers/parameterReducer.js
front/src/services/params.js

Reverts Ohtu-org/Serverless-data-parser-tool-for-project-proposals#104
Reverting a revert ":D"

Revert "Revert "Get's parameters from backend and adds to frontend left side field""

---

front/package-lock.json
front/package.json
front/src/components/Category.js
front/src/components/CategoryItem.js
front/src/reducers/assignReducer.js
front/src/tests/assignReducer.test.js

- Adds word editing in categories
- Updates assignReducer
- Adds documentation and tests

Category edit

---

codecov.yml

Added codecov configuartion file for excluding front-end code.

Codecov config file for excluding frontend code

---

front/src/components/CategoryItem.js

Fixes CategoryItem deletebutton

Frontend refactoring

---

cypress/integration/data_parser_spec.js
front/src/components/CategoryItem.js
front/src/components/DrawerParameters.js
front/src/components/JsonOfCategories.js

Json field

---

backend/utils/languageConstants.js

Gonna be merging myself, because I just added like 3 english words.

a couple of short english words

---

README.md
codecov.yml

Minor changes to README and codecov.yml. Will delete this branch when merged as it is useless for now.

Some minor changes

---

backend/app.js
backend/controllers/hubspotController.js
backend/services/hubspotService.js

First version of generic hubspot deal search.

Search deals by property

---

.gitignore
api/controllers/hubspotController.js
api/index.js
api/routes/searchHubspot.js
api/services/hubspotService.js
backend/app.js
backend/controllers/hubspotController.js
backend/services/hubspotService.js
front/src/reducers/channelReducer.js
front/src/services/searchDeals.js

Implement search by substring to aws lambda and create front service for it.

Aws hubspot search function

---

api/routes/messageShortcut.js
api/routes/slashCommand.js
api/utils/helpResponse.js
api/utils/parseResponse.js

Help command working.
Better / more correct responses to both slash command and message shortcut.

Helpfull parsa

---

api/controllers/hubspotController.js
api/services/hubspotService.js
backend/controllers/hubspotController.js
backend/services/hubspotService.js

Add new deal data to own properties in hubspot.

Createdeal hubspot properties

---

api/services/hubspotService.js

add property array to hubspot search request

add properties returned with query

---

front/src/components/HubSpotDeals/HubSpotDealTable.js

- Adds dealname to Customer field
- Adds amount to Price field

Populates price and customer

---

api/routes/sendToHubspot.js
api/routes/updateHubspot.js
front/package-lock.json
front/package.json
front/src/components/MessageBox.js
front/src/components/Page/PageLayout.js
front/src/reducers/sendReducer.js
front/src/reducers/userMessageReducer.js
front/src/services/sendToHubspot.js
front/src/store.js
front/src/tests/sendReducer.test.js

Create and updates generate UI message for the user.
Backend generates user messages and links.
Created new conditional messagebox to show them.

Create and update UI message

---

api/controllers/hubspotController.js
api/routes/updateHubspot.js

Fixed api HubspotController updateDeal to use deal.properties to find properties.

Update hubspot deal

---

api/tests/unit/assignCategoryToWord.test.js
api/utils/assignCategoryToWord.js
front/src/components/Words.js

Api adds Company category to words including a space. Frontend filter filters Company words.

Click less

---

api/services/slackService.js

fix optional parameter to slack query for private channels.

Include private channels

---

api/controllers/hubspotController.js

Update deal had gone corrupt due to changes in the frontend. Now working.

hubspot update fixed

---

api/index.js
api/routes/messageShortcut.js
api/routes/parseResult.js
api/routes/searchHubspot.js
api/routes/sendToHubspot.js
api/routes/slashCommand.js
api/routes/updateHubspot.js
api/tests/unit/slashCommand.test.js

Will anybody have the time to write the tests during this sprint.... doubt it.

Refactoring route-files to enable mock-testing them

---

api/tests/unit/assignCategoryToWord.test.js
api/utils/assignCategoryToWord.js

New names for categories to match frontend fields.

Api categories
